name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        uses: stefanoeb/jest-action@1.0.2
        with:
          jestArgs: --colors --coverage
